### ISSUE TITLE
Fail to create dynamic credential - 500 (request "Internal Server Error") Unexpected error.

### ISSUE THREAD

**Issue by Throckmortra** [hashicorp/vault-plugin-secrets-mongodbatlas#12]
Hello again!

I am not able to create programmatic api keys with the secrets engine.

```
Error reading mongodbatlas/creds/...: Error making API request.

URL: GET https://redacted/v1/mongodbatlas/creds/redacted
Code: 400. Errors:

* Error creating programmatic api key: POST https://cloud.mongodb.com/api/atlas/v1.0/orgs/redacted/apiKeys/redacted/whitelist: 500 (request "Internal Server Error") Unexpected error.
```

is there some way to get better logs of this event? I couldn't find anything in `journalctl`

The whitelist portion of the url made me think it was whitelist related but i confirmed that the vault ip was indeed whitelisted to the api key in the `mongodbatlas/config`.

**Comment by Throckmortra** [comment]
Actually I just noticed that it's actually creating the API keys! I see them in the API key section of our atlas dashboard. Vault just won't give them to me :'(

**Comment by Throckmortra** [comment]
Okay so I tried overwriting the role without IP and CIDR whitelists and they were sticky for some reason so I ended up having to delete and recreate the role without IP and CIDR whitelists and now I can retrieve the keys!

**Comment by Throckmortra** [comment]
Did the same thing with only IP whitelist and it still works. Guessing it is the CIDR block that is the issue

**Comment by swenson** [comment]
@Throckmortra I'm not able to reproduce this. When I follow the standard directions to create a role, i.e.,

```sh
vault write mongodbatlas/roles/myrole \
      project_id=xyz \
      roles=GROUP_CLUSTER_MANAGER \
      cidr_blocks=some.ip.goes.here/32 \
      ip_addresses=some.ip.goes.here
```

Are you still having this issue?

**Comment by Throckmortra** [comment]
I've kind of lost context on this issue and don't remember what we did to fix it or if it was even a valid bug in the end. You are welcome to close this

**Comment by swenson** [comment]
Thanks @Throckmortra. Sorry for the delay in getting back to you on this!
