### ISSUE TITLE
Support for Credentials with X.509 Authentication

### ISSUE THREAD

**Issue by jon-opal** [hashicorp/vault-plugin-secrets-mongodbatlas#19]
Thank you for this wonderful plugin! 

Currently, there is support for generating credentials for username/passwords for SCRAM authentication.

I am wondering if there is a plan to support the generation of credentials with X.509 certificates, for example using certificates that I manually upload to Atlas (https://docs.atlas.mongodb.com/security-self-managed-x509/)

**Comment by swenson** [comment]
Closing in favor of https://github.com/hashicorp/vault-plugin-database-mongodbatlas/issues/35
