### ISSUE TITLE
Support for Ops Manager/Cloud Manager

### ISSUE THREAD

**Issue by n3ph** [hashicorp/vault-plugin-secrets-mongodbatlas#25]
Hello! I don't know how possible this is, but I find myself in a situation where I am a user of Atlas, and Ops Manager. I've seen that the APIs are fairly similar but this plugin doesn't work with Ops Manager so I would need to do a lot of leg work to get this working with the plain MongoDB Database Plugin.

Are there any plans to make this compatible with Ops Manager as well?

**Comment by fairclothjm** [comment]
Thank you for submitting this request! For others who are interested in this, please stick a 👍 on this issue. We’re currently developing an internal process to review and prioritize feature requests.

**Comment by fairclothjm** [comment]
Hi, @n3ph We don't currently have plans for Ops Manager. Please feel free to contact our Product team if you are still interested in this. As this is not directly related to this plugin I am going to close this issue.
